# Generated by Django 6.0.3 on 2026-07-28 14:55

import academico.validators
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=6, unique=True)),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("semipresencial", "Semipresencial"),
                            ("online", "Online"),
                        ],
                        default="presencial",
                        max_length=20,
                    ),
                ),
                (
                    "duracion_semestres",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(4),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "cupo_maximo",
                    models.PositiveIntegerField(
                        default=40,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Carrera",
                "verbose_name_plural": "Carreras",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "cedula",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[academico.validators.validar_cedula],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=15)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("fecha_ingreso", models.DateField(default=datetime.date.today)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("egresado", "Egresado"),
                            ("retirado", "Retirado"),
                        ],
                        default="activo",
                        max_length=15,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "carrera_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudiantes",
                        to="academico.carrera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "periodo",
                    models.CharField(
                        choices=[("2026-01", "2026-01"), ("2026-02", "2026-02")],
                        max_length=10,
                    ),
                ),
                ("asignatura", models.CharField(max_length=100)),
                (
                    "creditos",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "costo_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=25.0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("fecha", models.DateField(default=datetime.date.today)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("confirmada", "Confirmada"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=15,
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
                (
                    "estudiante_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matriculas",
                        to="academico.estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matrícula",
                "verbose_name_plural": "Matrículas",
                "ordering": ["-fecha"],
            },
        ),
    ]
